services:
    app:
        image: lebazaar-app-staging:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/vhost.conf:/opt/docker/etc/nginx/vhost.conf:ro
            - /var/log/app:/app/storage/logs
            - /var/log/nginx/:/var/log/nginx
        environment:
            USE_SECRETS_MANAGER: "true"
            SECRETS_MANAGER_NAME: "lebazaar/staging"
            AWS_REGION: "ap-northeast-1"
            LOG_STDOUT: '/var/log/nginx/access.log'
            LOG_STDERR: '/var/log/nginx/error.log'
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
            interval: 30s
            timeout: 3s
            start_period: 40s
            retries: 3
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1.5G
                reservations:
                    cpus: '0.25'
                    memory: 256M
